"""update_to_agent_v2

Revision ID: 55bdaa0adab2
Revises: 4a7df905900c
Create Date: 2026-03-16 21:37:58.785072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bdaa0adab2'
down_revision: Union[str, None] = '4a7df905900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_notified')
    # ### end Alembic commands ###
